title: Climate Health
tagline: University of Bristol
description: Climate and Health research group at the University of Bristol, led by Professor Dann Mitchell and Dr Eunice Lo.
email: climatechange-health@bristol.ac.uk
# GitHub Pages project site. For local preview use:  bundle exec jekyll serve --baseurl ""
url: "https://alexodavies.github.io"
baseurl: "/bristol-climate-health-page"

social:
  github: ""
  twitter: ""
  youtube: ""

collections:
  members:
    output: true
    permalink: /members/:name.html

defaults:
  - scope: { path: "", type: "pages" }
    values: { layout: "page" }
  - scope: { path: "", type: "members" }
    values: { layout: "member" }
  - scope: { path: "", type: "posts" }
    values: { layout: "post" }

timezone: Europe/London
permalink: /blog/:year/:month/:day/:title.html
exclude: [assets/video/hero.mp4, Gemfile, Gemfile.lock, scripts, README.md, vendor]
